### ISSUE TITLE
Bot personality interfering in faq

### ISSUE THREAD

**Issue by fredmarques** [fczuardi/calamarcopollo#100]
![badanswer](https://cloud.githubusercontent.com/assets/8461400/16267136/81350a98-385e-11e6-9a31-a052e21c0ea5.png)

**Comment by GabrielSoga** [comment]
I'm training this on wit for those cases.
But the ideal resolution is to change priorities due to entities interference, such as #89 suggestion

**Comment by GabrielSoga** [comment]
"Gato" was reserved as a keyword in wit. Now, for personality phrases, it's treated as trait

**Comment by GabrielSoga** [comment]
I'm having a big problem related to #107 . Don't know how this could be fixed

**Comment by GabrielSoga** [comment]
Solved by #113
