### ISSUE TITLE
Rio Claro, SP

### ISSUE THREAD

**Issue by fczuardi** [fczuardi/calamarcopollo#122]
### Current behavior:

If the user asks for Rio Claro, SP, Rio Claro, RJ is always returned.

### Expected behavior:

Maybe a buttons choice for cases like this, or in the case of "rio claro, sp" as the input, recognize the right city without extra prompts.

**Comment by GabrielSoga** [comment]
Solved with training, without buttons
"Rio claro sp pra sp" works well
