### ISSUE TITLE
Answer to "duvida, informação, questão" and others

### ISSUE THREAD

**Issue by isadoramariamendes** [fczuardi/calamarcopollo#124]
Current behavior:

If the user asks for information, in the very beginning Bigode just ignores and ask the destination (that's been happening a lot, btw).
In the second user try, he returns "Desculpa, mas não encontrei informações de duvida 😶.".  
This is a common way that the user may introduce his and her conversation before actually buying the ticket, so it should be fixed.
See an example: 
![img_0229](https://cloud.githubusercontent.com/assets/9004719/16487251/ee89c204-3e9f-11e6-9396-95a8f1a9f113.PNG)

Expected behavior:

Answer something generic in this cases, such as "Como posso te ajudar?", "Qual é a sua dúvida?", or "Qual informação voce precisa?"

**Comment by fczuardi** [comment]
moved to https://github.com/calamar-io/calamarcopollo/issues/7
