### ISSUE TITLE
[bigode] tripDialog.js "Comprar" button

### ISSUE THREAD

**Issue by GabrielSoga** [fczuardi/calamarcopollo#55]
We should replace the title:"Comprar" to "Checar", which is a lot less aggressive to user, stimulating him to click and try.

**Comment by GabrielSoga** [comment]
![buy](https://cloud.githubusercontent.com/assets/19688935/16129263/86b86a56-33da-11e6-8b57-da9ac5f760c3.png)

**Comment by fczuardi** [comment]
We should move this string out of the calamarcopollo code and into the replies folder, so we can customize it as well

**Comment by fczuardi** [comment]
fixed with 6d1717c48c983343068ec345c47c6ef992e88c5b
