### ISSUE TITLE
[bigode] improve "about" and bot background answers

### ISSUE THREAD

**Issue by fczuardi** [fczuardi/calamarcopollo#71]
![screen shot 2016-06-20 at 12 11 35 pm](https://cloud.githubusercontent.com/assets/7760/16199508/2ead80ea-36e0-11e6-8236-479c7a34644f.png)

**Comment by GabrielSoga** [comment]
We could create three new routes:

If someone ask for the name origin:
nameOrigin: `Meu nome? Dá só uma olhada nesses meus lindos bigodes naturais de humano!`,
  
If someone asks if he's a cat:
isCat: `GATO? EU? 🙀\nPor acaso vc já viu algum gato trabalhando em companhia de ônibus, ainda mais com bigodes tão legais assim??`,

If someone asks if he's a bot:
isBot: `O que é um bot?🔊 (ele ainda tá na versão ${bigodeVersion})\n\nEi, quem disse isso? Isso é uma data?\n`
