### ISSUE TITLE
reply to reactions such as "hahaha" "kkk"

### ISSUE THREAD

**Issue by fczuardi** [fczuardi/calamarcopollo#79]
![screen shot 2016-06-20 at 1 38 56 pm](https://cloud.githubusercontent.com/assets/7760/16202571/916971e2-36ec-11e6-8315-d5b49b6a455e.png)

**Comment by GabrielSoga** [comment]
The bot should answer laughs generally. Using emojis (😆) may be a good idea.

**Comment by fczuardi** [comment]
😆 might be related to bug #90 I am closing this one as resolved
