### ISSUE TITLE
Maybe bot should ask in a situation like this

### ISSUE THREAD

**Issue by fredmarques** [fczuardi/calamarcopollo#83]
When we got the same name for both cities (source and destination), maybe the bot could ask which city user wants to use as **source** and which as **destination**.

![botshouldaskinthiscase](https://cloud.githubusercontent.com/assets/8461400/16202742/6eff7204-36ed-11e6-80ef-a912a2f80bc9.png)

**Comment by fczuardi** [comment]
Alegre, ES and Pouso Alegre, MG are different cities, but yes… your suggestion can be implemented as a fix for #72

**Comment by fczuardi** [comment]
dupe of #72
