### ISSUE TITLE
Why bot can't recognize MG? What About "Pouso Alegre"?

### ISSUE THREAD

**Issue by fredmarques** [fczuardi/calamarcopollo#85]
Here we ave a city and a **city** and **state**. Bot can't recognize neither.

![wtfmg](https://cloud.githubusercontent.com/assets/8461400/16202912/2e23d800-36ee-11e6-93fe-fc2507c42e23.png)

**Comment by fczuardi** [comment]
related #81

**Comment by fczuardi** [comment]
works for me
